# Generated by Django 5.0 on 2024-02-17 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('estimate_end', models.DateField()),
                ('preority', models.IntegerField(default=3)),
            ],
        ),
    ]
